"""
Django settings for costcontrol project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'melcom-cost-control-portal-key-2026-xK9#mP2$nQ7@wL'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '10.10.1.79', 'localhost', '127.0.0.1']

# Allow uploads up to 60 MB (covers photos + short videos)
DATA_UPLOAD_MAX_MEMORY_SIZE = 62_914_560   # 60 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 62_914_560   # 60 MB

# CSRF — allow all internal network origins (Capacitor app + browsers)
CSRF_TRUSTED_ORIGINS = [
    'http://10.10.1.79:8507',
    'http://localhost:8507',
    'http://127.0.0.1:8507',
    'http://192.168.0.60:8507',
]
CSRF_COOKIE_SAMESITE  = 'Lax'    # works for same-origin browser navigation
CSRF_COOKIE_HTTPONLY  = False     # Capacitor WebView needs to read the cookie
SESSION_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wastage',
    'product_scanner',
]

# ── AI Vision provider ──────────────────────────────────────────────────────
# Set AI_VISION_PROVIDER env var to 'openai' to use ChatGPT-4o instead
import os as _os
ANTHROPIC_API_KEY    = _os.environ.get("ANTHROPIC_API_KEY", "")
OPENAI_API_KEY       = _os.environ.get("OPENAI_API_KEY", "")
AI_VISION_PROVIDER   = _os.environ.get("AI_VISION_PROVIDER", "anthropic")  # 'anthropic' | 'openai'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'costcontrol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'costcontrol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cost_control_portal',
        'USER': 'postgres',
        'PASSWORD': 'hello',
        'HOST': 'localhost',
        'PORT': '3307',
    }
}

# Network drive path for incident photos/videos (primary storage — no local copy)
INCIDENT_MEDIA_ROOT = r'\\10.10.0.30\mis\wastagecontrol'

# ── AI Analyst Chat (analytics dashboard bot widget) ────────────────────────
# Provider: 'ollama' (local, free) or 'anthropic' (paid, needs API key)
AI_PROVIDER = 'ollama'

# Ollama settings (used when AI_PROVIDER = 'ollama')
# Install Ollama: https://ollama.com/download  → then run: ollama pull llama3.2
OLLAMA_URL   = 'http://localhost:11434'   # Ollama server (usually same machine)
OLLAMA_MODEL = 'llama3.2'                # or 'mistral', 'llama3.1:8b', 'codellama'

# Anthropic settings (used only when AI_PROVIDER = 'anthropic')
ANTHROPIC_API_KEY = ''


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Accra'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

SESSION_COOKIE_AGE = 28800
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ── Mobile / Cross-origin support ─────────────────────────────────────────────
# Allow CSRF from LAN IP ranges (Android WebView and Capacitor use the server URL directly,
# so Django sees requests from the device's LAN IP. These origins must be trusted.)
CSRF_TRUSTED_ORIGINS = [
    'http://10.10.0.1:8507',
    'http://10.10.0.2:8507',
    'http://10.10.0.3:8507',
    'http://10.10.0.4:8507',
    'http://10.10.0.5:8507',
    'http://10.10.0.6:8507',
    'http://10.10.0.7:8507',
    'http://10.10.0.8:8507',
    'http://10.10.0.9:8507',
    'http://10.10.0.10:8507',
    'http://10.10.0.11:8507',
    'http://10.10.0.12:8507',
    'http://10.10.0.13:8507',
    'http://10.10.0.14:8507',
    'http://10.10.0.15:8507',
    'http://10.10.0.20:8507',
    'http://10.10.0.30:8507',
    'http://10.10.0.50:8507',
    'http://10.10.0.100:8507',
    'http://localhost:8507',
    'http://127.0.0.1:8507',
]

# Allow session cookies to be sent from WebView (needed on Android 9+)
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE   = False   # Set True only when serving over HTTPS
