# Generated by Django 6.0.4 on 2026-05-13 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('product_type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=60, null=True)),
                ('units_per_case', models.IntegerField(blank=True, null=True)),
                ('num_cases', models.IntegerField(blank=True, null=True)),
                ('num_pieces', models.IntegerField(blank=True, null=True)),
                ('total_units', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('weight_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_alcohol', models.BooleanField(default=False)),
                ('alcohol_type', models.CharField(blank=True, max_length=100, null=True)),
                ('alcohol_subtype', models.CharField(blank=True, max_length=200, null=True)),
                ('bottle_size_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fill_level_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ml_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alcohol_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=60, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('ai_notes', models.TextField(blank=True, null=True)),
                ('raw_ai_response', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=80, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
