# Generated by Django 5.2.13 on 2026-05-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscan',
            name='scale_reading',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
