# Generated by Django 5.2.13 on 2026-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_scanner', '0002_productscan_scale_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscan',
            name='grammage',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='productscan',
            name='has_expiry',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productscan',
            name='is_fnv',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
