"""
LangChain orchestration layer - LLM chains and agents
"""
import logging
import re
from typing import Tuple, Optional
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import StrOutputParser
from config import config

logger = logging.getLogger(__name__)

class LLMOrchestrator:
    """Orchestrates LLM operations with fallback support"""
    
    def __init__(self):
        """Initialize LLM clients"""
        self.openai_client = None
        self.gemini_client = None
        self.fallback_order = ["openai", "gemini"]
        
        if config.OPENAI_API_KEY:
            self.openai_client = ChatOpenAI(
                api_key=config.OPENAI_API_KEY,
                model=config.OPENAI_MODEL,
                temperature=0.3
            )
            logger.info("✅ OpenAI LLM initialized")
        
        if config.GEMINI_API_KEY:
            self.gemini_client = ChatGoogleGenerativeAI(
                google_api_key=config.GEMINI_API_KEY,
                model=config.GEMINI_MODEL,
                temperature=0.3
            )
            logger.info("✅ Gemini LLM initialized")
    
    def generate_sql(self, user_question: str) -> Tuple[str, str]:
        """Generate safe SQL from natural language question"""
        
        guidance = f"""
You are a strict PostgreSQL SQL generator for retail analytics.
Generate ONE safe SELECT query only.

Available tables:
- mv_century_penetration: stock_status, total_stock, sales_30d, req_21_days, item_code, shop_code
- sales_2024, sales_2025, sales_2026: sales amounts, dates, shops, items
- inventory_master: stock levels, item codes
- itemdetails: product info, departments, groups

Rules:
1. ONLY SELECT queries allowed
2. Include LIMIT {config.MAX_QUERY_RESULTS}
3. Use meaningful ORDER BY
4. Return SQL only, no explanations
5. No semicolons

User question: {user_question}
Generate SQL:
"""
        
        try:
            # Try primary LLM
            if self.openai_client:
                response = self.openai_client.invoke(guidance)
                sql = response.content.strip()
                logger.info("✅ SQL generated by OpenAI")
                return self._sanitize_sql(sql), "openai"
            elif self.gemini_client:
                response = self.gemini_client.invoke(guidance)
                sql = response.content.strip()
                logger.info("✅ SQL generated by Gemini")
                return self._sanitize_sql(sql), "gemini"
            else:
                raise RuntimeError("❌ No LLM provider available")
                
        except Exception as e:
            logger.error(f"❌ SQL generation failed: {str(e)}")
            raise
    
    def generate_insights(self, question: str, data_summary: str, sample_rows: int) -> Tuple[str, str]:
        """Generate insights from query results"""
        
        guidance = f"""
You are a retail analytics expert. Provide 2-3 crisp, actionable insights.
Be specific with numbers and percentages.

User asked: {question}
Data returned: {sample_rows} rows
Summary: {data_summary}

Insights (2-3 bullets, max 150 chars each):
"""
        
        try:
            if self.openai_client:
                response = self.openai_client.invoke(guidance)
                logger.info("✅ Insights generated by OpenAI")
                return response.content.strip(), "openai"
            elif self.gemini_client:
                response = self.gemini_client.invoke(guidance)
                logger.info("✅ Insights generated by Gemini")
                return response.content.strip(), "gemini"
            else:
                raise RuntimeError("❌ No LLM provider available")
                
        except Exception as e:
            logger.error(f"❌ Insight generation failed: {str(e)}")
            raise
    
    @staticmethod
    def _sanitize_sql(sql: str) -> str:
        """Validate and sanitize SQL"""
        
        sql = sql.strip()
        
        # Remove markdown
        if sql.startswith("```"):
            sql = re.sub(r"^```(sql)?\n", "", sql)
            sql = re.sub(r"\n```$", "", sql)
        
        sql = sql.rstrip(";")
        
        # Check for blocked keywords
        for keyword in config.BLOCKED_KEYWORDS:
            if re.search(rf"\b{keyword}\b", sql, re.IGNORECASE):
                raise ValueError(f"❌ Blocked keyword: {keyword}")
        
        # Ensure SELECT query
        if not re.match(r"^\s*SELECT", sql, re.IGNORECASE):
            raise ValueError("❌ Only SELECT queries allowed")
        
        # Add LIMIT if missing
        if "LIMIT" not in sql.upper():
            sql = f"{sql} LIMIT {config.MAX_QUERY_RESULTS}"
        
        logger.info(f"✅ SQL validated: {sql[:80]}...")
        return sql

# Global orchestrator instance
llm_orchestrator = LLMOrchestrator()
