# Generated by Django 6.0.4 on 2026-04-21 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_no', models.CharField(max_length=30, unique=True)),
                ('shop_code', models.CharField(max_length=20)),
                ('shop_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Bakery', 'Bakery'), ('Kitchen', 'Kitchen'), ('Retail', 'Retail')], max_length=50)),
                ('submitted_by', models.CharField(max_length=20)),
                ('submitted_name', models.CharField(blank=True, max_length=100)),
                ('item_code', models.CharField(default='AAAAA', max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(choices=[('Expired', 'Expired'), ('Over Production', 'Over Production'), ('Damage', 'Damage'), ('Quality Issue', 'Quality Issue'), ('Handling Error', 'Handling Error'), ('Others', 'Others')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=20, null=True)),
                ('approved_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('video_path', models.TextField(blank=True, null=True)),
                ('photo_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('video_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wastage Incident',
                'verbose_name_plural': 'Wastage Incidents',
                'db_table': 'cc_incident',
                'ordering': ['-submit_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(default='AAAAA', max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('grp', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_group', models.CharField(blank=True, max_length=100, null=True)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(choices=[('RAW', 'RAW'), ('Finished', 'Finished'), ('Packaging', 'Packaging')], default='Finished', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Master',
                'db_table': 'cc_item_master',
            },
        ),
        migrations.CreateModel(
            name='MediaRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_no', models.CharField(max_length=30)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_path', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Registry',
                'db_table': 'cc_media_registry',
            },
        ),
        migrations.CreateModel(
            name='ShopStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('shop_code', models.CharField(max_length=20)),
                ('shop_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor'), ('manager', 'Store Manager')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='wastage.shopstaff', to_field='emp_id')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Staff',
                'verbose_name_plural': 'Shop Staff',
                'db_table': 'cc_shop_staff',
            },
        ),
    ]
