# Generated by Django 6.0.4 on 2026-04-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopstaff',
            name='managed_shops',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reason',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Over Production', 'Over Production'), ('Damage', 'Damage'), ('Quality Issue', 'Quality Issue'), ('Handling Error', 'Handling Error'), ('No Wastage', 'No Wastage'), ('Others', 'Others')], max_length=30),
        ),
    ]
