# Generated by Django 6.0.4 on 2026-04-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0002_add_managed_shops_and_system_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='photo_exif_sig',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo_phash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='video_meta_sig',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mediaregistry',
            name='exif_signature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mediaregistry',
            name='perceptual_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
